/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/reverse/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIpv6s implements Ipv6Interface
type FakeIpv6s struct {
	Fake *FakeReverseV1alpha1
	ns   string
}

var ipv6sResource = schema.GroupVersionResource{Group: "reverse.vultr.kubeform.com", Version: "v1alpha1", Resource: "ipv6s"}

var ipv6sKind = schema.GroupVersionKind{Group: "reverse.vultr.kubeform.com", Version: "v1alpha1", Kind: "Ipv6"}

// Get takes name of the ipv6, and returns the corresponding ipv6 object, and an error if there is any.
func (c *FakeIpv6s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Ipv6, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipv6sResource, c.ns, name), &v1alpha1.Ipv6{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ipv6), err
}

// List takes label and field selectors, and returns the list of Ipv6s that match those selectors.
func (c *FakeIpv6s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.Ipv6List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipv6sResource, ipv6sKind, c.ns, opts), &v1alpha1.Ipv6List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.Ipv6List{ListMeta: obj.(*v1alpha1.Ipv6List).ListMeta}
	for _, item := range obj.(*v1alpha1.Ipv6List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ipv6s.
func (c *FakeIpv6s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipv6sResource, c.ns, opts))

}

// Create takes the representation of a ipv6 and creates it.  Returns the server's representation of the ipv6, and an error, if there is any.
func (c *FakeIpv6s) Create(ctx context.Context, ipv6 *v1alpha1.Ipv6, opts v1.CreateOptions) (result *v1alpha1.Ipv6, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipv6sResource, c.ns, ipv6), &v1alpha1.Ipv6{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ipv6), err
}

// Update takes the representation of a ipv6 and updates it. Returns the server's representation of the ipv6, and an error, if there is any.
func (c *FakeIpv6s) Update(ctx context.Context, ipv6 *v1alpha1.Ipv6, opts v1.UpdateOptions) (result *v1alpha1.Ipv6, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipv6sResource, c.ns, ipv6), &v1alpha1.Ipv6{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ipv6), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIpv6s) UpdateStatus(ctx context.Context, ipv6 *v1alpha1.Ipv6, opts v1.UpdateOptions) (*v1alpha1.Ipv6, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipv6sResource, "status", c.ns, ipv6), &v1alpha1.Ipv6{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ipv6), err
}

// Delete takes name of the ipv6 and deletes it. Returns an error if one occurs.
func (c *FakeIpv6s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipv6sResource, c.ns, name), &v1alpha1.Ipv6{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIpv6s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipv6sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.Ipv6List{})
	return err
}

// Patch applies the patch and returns the patched ipv6.
func (c *FakeIpv6s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Ipv6, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipv6sResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ipv6{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ipv6), err
}
