/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	startupv1alpha1 "kubeform.dev/provider-vultr-api/apis/startup/v1alpha1"
	versioned "kubeform.dev/provider-vultr-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-vultr-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-vultr-api/client/listers/startup/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScriptInformer provides access to a shared informer and lister for
// Scripts.
type ScriptInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ScriptLister
}

type scriptInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScriptInformer constructs a new informer for Script type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScriptInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScriptInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScriptInformer constructs a new informer for Script type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScriptInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StartupV1alpha1().Scripts(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StartupV1alpha1().Scripts(namespace).Watch(context.TODO(), options)
			},
		},
		&startupv1alpha1.Script{},
		resyncPeriod,
		indexers,
	)
}

func (f *scriptInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScriptInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scriptInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&startupv1alpha1.Script{}, f.defaultInformer)
}

func (f *scriptInformer) Lister() v1alpha1.ScriptLister {
	return v1alpha1.NewScriptLister(f.Informer().GetIndexer())
}
