/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/kubernetes/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKuberneteses implements KubernetesInterface
type FakeKuberneteses struct {
	Fake *FakeKubernetesV1alpha1
	ns   string
}

var kubernetesesResource = schema.GroupVersionResource{Group: "kubernetes.vultr.kubeform.com", Version: "v1alpha1", Resource: "kuberneteses"}

var kubernetesesKind = schema.GroupVersionKind{Group: "kubernetes.vultr.kubeform.com", Version: "v1alpha1", Kind: "Kubernetes"}

// Get takes name of the kubernetes, and returns the corresponding kubernetes object, and an error if there is any.
func (c *FakeKuberneteses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubernetesesResource, c.ns, name), &v1alpha1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kubernetes), err
}

// List takes label and field selectors, and returns the list of Kuberneteses that match those selectors.
func (c *FakeKuberneteses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubernetesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubernetesesResource, kubernetesesKind, c.ns, opts), &v1alpha1.KubernetesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KubernetesList{ListMeta: obj.(*v1alpha1.KubernetesList).ListMeta}
	for _, item := range obj.(*v1alpha1.KubernetesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kuberneteses.
func (c *FakeKuberneteses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubernetesesResource, c.ns, opts))

}

// Create takes the representation of a kubernetes and creates it.  Returns the server's representation of the kubernetes, and an error, if there is any.
func (c *FakeKuberneteses) Create(ctx context.Context, kubernetes *v1alpha1.Kubernetes, opts v1.CreateOptions) (result *v1alpha1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubernetesesResource, c.ns, kubernetes), &v1alpha1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kubernetes), err
}

// Update takes the representation of a kubernetes and updates it. Returns the server's representation of the kubernetes, and an error, if there is any.
func (c *FakeKuberneteses) Update(ctx context.Context, kubernetes *v1alpha1.Kubernetes, opts v1.UpdateOptions) (result *v1alpha1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubernetesesResource, c.ns, kubernetes), &v1alpha1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kubernetes), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKuberneteses) UpdateStatus(ctx context.Context, kubernetes *v1alpha1.Kubernetes, opts v1.UpdateOptions) (*v1alpha1.Kubernetes, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubernetesesResource, "status", c.ns, kubernetes), &v1alpha1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kubernetes), err
}

// Delete takes name of the kubernetes and deletes it. Returns an error if one occurs.
func (c *FakeKuberneteses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubernetesesResource, c.ns, name), &v1alpha1.Kubernetes{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKuberneteses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubernetesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KubernetesList{})
	return err
}

// Patch applies the patch and returns the patched kubernetes.
func (c *FakeKuberneteses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Kubernetes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubernetesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Kubernetes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kubernetes), err
}
