/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/reserved/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIps implements IpInterface
type FakeIps struct {
	Fake *FakeReservedV1alpha1
	ns   string
}

var ipsResource = schema.GroupVersionResource{Group: "reserved.vultr.kubeform.com", Version: "v1alpha1", Resource: "ips"}

var ipsKind = schema.GroupVersionKind{Group: "reserved.vultr.kubeform.com", Version: "v1alpha1", Kind: "Ip"}

// Get takes name of the ip, and returns the corresponding ip object, and an error if there is any.
func (c *FakeIps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Ip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipsResource, c.ns, name), &v1alpha1.Ip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ip), err
}

// List takes label and field selectors, and returns the list of Ips that match those selectors.
func (c *FakeIps) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IpList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipsResource, ipsKind, c.ns, opts), &v1alpha1.IpList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IpList{ListMeta: obj.(*v1alpha1.IpList).ListMeta}
	for _, item := range obj.(*v1alpha1.IpList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ips.
func (c *FakeIps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipsResource, c.ns, opts))

}

// Create takes the representation of a ip and creates it.  Returns the server's representation of the ip, and an error, if there is any.
func (c *FakeIps) Create(ctx context.Context, ip *v1alpha1.Ip, opts v1.CreateOptions) (result *v1alpha1.Ip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipsResource, c.ns, ip), &v1alpha1.Ip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ip), err
}

// Update takes the representation of a ip and updates it. Returns the server's representation of the ip, and an error, if there is any.
func (c *FakeIps) Update(ctx context.Context, ip *v1alpha1.Ip, opts v1.UpdateOptions) (result *v1alpha1.Ip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipsResource, c.ns, ip), &v1alpha1.Ip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ip), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIps) UpdateStatus(ctx context.Context, ip *v1alpha1.Ip, opts v1.UpdateOptions) (*v1alpha1.Ip, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipsResource, "status", c.ns, ip), &v1alpha1.Ip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ip), err
}

// Delete takes name of the ip and deletes it. Returns an error if one occurs.
func (c *FakeIps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipsResource, c.ns, name), &v1alpha1.Ip{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IpList{})
	return err
}

// Patch applies the patch and returns the patched ip.
func (c *FakeIps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Ip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Ip{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Ip), err
}
