/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/iso/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrivates implements PrivateInterface
type FakePrivates struct {
	Fake *FakeIsoV1alpha1
	ns   string
}

var privatesResource = schema.GroupVersionResource{Group: "iso.vultr.kubeform.com", Version: "v1alpha1", Resource: "privates"}

var privatesKind = schema.GroupVersionKind{Group: "iso.vultr.kubeform.com", Version: "v1alpha1", Kind: "Private"}

// Get takes name of the private, and returns the corresponding private object, and an error if there is any.
func (c *FakePrivates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Private, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(privatesResource, c.ns, name), &v1alpha1.Private{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Private), err
}

// List takes label and field selectors, and returns the list of Privates that match those selectors.
func (c *FakePrivates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrivateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(privatesResource, privatesKind, c.ns, opts), &v1alpha1.PrivateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PrivateList{ListMeta: obj.(*v1alpha1.PrivateList).ListMeta}
	for _, item := range obj.(*v1alpha1.PrivateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested privates.
func (c *FakePrivates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(privatesResource, c.ns, opts))

}

// Create takes the representation of a private and creates it.  Returns the server's representation of the private, and an error, if there is any.
func (c *FakePrivates) Create(ctx context.Context, private *v1alpha1.Private, opts v1.CreateOptions) (result *v1alpha1.Private, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(privatesResource, c.ns, private), &v1alpha1.Private{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Private), err
}

// Update takes the representation of a private and updates it. Returns the server's representation of the private, and an error, if there is any.
func (c *FakePrivates) Update(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (result *v1alpha1.Private, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(privatesResource, c.ns, private), &v1alpha1.Private{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Private), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrivates) UpdateStatus(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (*v1alpha1.Private, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(privatesResource, "status", c.ns, private), &v1alpha1.Private{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Private), err
}

// Delete takes name of the private and deletes it. Returns an error if one occurs.
func (c *FakePrivates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(privatesResource, c.ns, name), &v1alpha1.Private{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrivates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(privatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PrivateList{})
	return err
}

// Patch applies the patch and returns the patched private.
func (c *FakePrivates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Private, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(privatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Private{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Private), err
}
