/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/iso/v1alpha1"
	scheme "kubeform.dev/provider-vultr-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrivatesGetter has a method to return a PrivateInterface.
// A group's client should implement this interface.
type PrivatesGetter interface {
	Privates(namespace string) PrivateInterface
}

// PrivateInterface has methods to work with Private resources.
type PrivateInterface interface {
	Create(ctx context.Context, private *v1alpha1.Private, opts v1.CreateOptions) (*v1alpha1.Private, error)
	Update(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (*v1alpha1.Private, error)
	UpdateStatus(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (*v1alpha1.Private, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Private, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PrivateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Private, err error)
	PrivateExpansion
}

// privates implements PrivateInterface
type privates struct {
	client rest.Interface
	ns     string
}

// newPrivates returns a Privates
func newPrivates(c *IsoV1alpha1Client, namespace string) *privates {
	return &privates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the private, and returns the corresponding private object, and an error if there is any.
func (c *privates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Private, err error) {
	result = &v1alpha1.Private{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Privates that match those selectors.
func (c *privates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrivateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrivateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested privates.
func (c *privates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("privates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a private and creates it.  Returns the server's representation of the private, and an error, if there is any.
func (c *privates) Create(ctx context.Context, private *v1alpha1.Private, opts v1.CreateOptions) (result *v1alpha1.Private, err error) {
	result = &v1alpha1.Private{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("privates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(private).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a private and updates it. Returns the server's representation of the private, and an error, if there is any.
func (c *privates) Update(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (result *v1alpha1.Private, err error) {
	result = &v1alpha1.Private{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privates").
		Name(private.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(private).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *privates) UpdateStatus(ctx context.Context, private *v1alpha1.Private, opts v1.UpdateOptions) (result *v1alpha1.Private, err error) {
	result = &v1alpha1.Private{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privates").
		Name(private.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(private).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the private and deletes it. Returns an error if one occurs.
func (c *privates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *privates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched private.
func (c *privates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Private, err error) {
	result = &v1alpha1.Private{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("privates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
