/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vultr-api/apis/bare/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetalServers implements MetalServerInterface
type FakeMetalServers struct {
	Fake *FakeBareV1alpha1
	ns   string
}

var metalserversResource = schema.GroupVersionResource{Group: "bare.vultr.kubeform.com", Version: "v1alpha1", Resource: "metalservers"}

var metalserversKind = schema.GroupVersionKind{Group: "bare.vultr.kubeform.com", Version: "v1alpha1", Kind: "MetalServer"}

// Get takes name of the metalServer, and returns the corresponding metalServer object, and an error if there is any.
func (c *FakeMetalServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MetalServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(metalserversResource, c.ns, name), &v1alpha1.MetalServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalServer), err
}

// List takes label and field selectors, and returns the list of MetalServers that match those selectors.
func (c *FakeMetalServers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MetalServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(metalserversResource, metalserversKind, c.ns, opts), &v1alpha1.MetalServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetalServerList{ListMeta: obj.(*v1alpha1.MetalServerList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetalServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metalServers.
func (c *FakeMetalServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(metalserversResource, c.ns, opts))

}

// Create takes the representation of a metalServer and creates it.  Returns the server's representation of the metalServer, and an error, if there is any.
func (c *FakeMetalServers) Create(ctx context.Context, metalServer *v1alpha1.MetalServer, opts v1.CreateOptions) (result *v1alpha1.MetalServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(metalserversResource, c.ns, metalServer), &v1alpha1.MetalServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalServer), err
}

// Update takes the representation of a metalServer and updates it. Returns the server's representation of the metalServer, and an error, if there is any.
func (c *FakeMetalServers) Update(ctx context.Context, metalServer *v1alpha1.MetalServer, opts v1.UpdateOptions) (result *v1alpha1.MetalServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(metalserversResource, c.ns, metalServer), &v1alpha1.MetalServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMetalServers) UpdateStatus(ctx context.Context, metalServer *v1alpha1.MetalServer, opts v1.UpdateOptions) (*v1alpha1.MetalServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(metalserversResource, "status", c.ns, metalServer), &v1alpha1.MetalServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalServer), err
}

// Delete takes name of the metalServer and deletes it. Returns an error if one occurs.
func (c *FakeMetalServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(metalserversResource, c.ns, name), &v1alpha1.MetalServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetalServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(metalserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetalServerList{})
	return err
}

// Patch applies the patch and returns the patched metalServer.
func (c *FakeMetalServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MetalServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(metalserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.MetalServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalServer), err
}
